### ISSUE TITLE
Add usage with blazor

### ISSUE THREAD

**Issue by NUlliiON** [ImpromptuNinjas/UltralightSharp#1]
I experimented with the <b>Blazor</b> and your Ultralight bindings. It turned out something like this "https://github.com/NUlliiON/UltralightBlazorExperiment", can you add a link to my experiment?

**Comment by Tyler-IN** [comment]
https://github.com/ImpromptuNinjas/UltralightSharp/blob/master/README.md#usage-in-blazor

**Comment by NUlliiON** [comment]
Thanks :)
